name: Kwiki-PreformattedBlocks
version: 0.10
abstract: Kwiki Preformatted Blocks Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.31
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
